apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-audit-rest-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/log/kube-audit-rest  # Host 경로
    type: DirectoryOrCreate

