apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-audit-rest-pvc
  namespace: kube-audit-rest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: kube-audit-rest-pv