apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: journal-exporter
  namespace: amazon-cloudwatch
spec:
  selector:
    matchLabels:
      app: journal-exporter
  template:
    metadata:
      labels:
        app: journal-exporter
    spec:
      hostPID: true
      hostNetwork: true
      tolerations:
      - operator: Exists
      containers:
      - name: journalctl
        image: busybox:1.36
        securityContext:
          privileged: true
        command: ["/bin/sh","-lc"]
        args:
        - |
          nsenter --target 1 --mount --uts --ipc --net --pid -- \
            /bin/sh -lc 'exec journalctl -f -o json' > /var/log/journal.log
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        hostPath:
          path: /var/log

