apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 432128687171.dkr.ecr.ap-northeast-2.amazonaws.com/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
#          resources:
#            requests:
#              cpu: "30m"
#              memory: "64Mi"
#            limits:
#              cpu: "50m"
#              memory: "64Mi"
